from sqlalchemy.ext.asyncio import AsyncEngine

async def ensure_tz_tables(engine: AsyncEngine) -> None:
    async with engine.begin() as conn:
        await conn.exec_driver_sql("""
        ALTER TABLE users ADD COLUMN IF NOT EXISTS supervisor_id bigint REFERENCES users(id) ON DELETE SET NULL
        """)
        await conn.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_users_supervisor_id ON users(supervisor_id)")
        # Workflow is now explicitly started per interaction. The old schema trigger
        # instantiated stages at interaction creation, which made template changes
        # destructive/ambiguous. Existing stage rows are preserved; new interactions
        # receive stages only from POST /interactions/{id}/workflow/start.
        await conn.exec_driver_sql("DROP TRIGGER IF EXISTS interactions_instantiate_workflow ON interactions")
        await conn.exec_driver_sql("""
        INSERT INTO roles(code,name,description) VALUES
          ('leader','Leader','Руководитель менеджеров'),
          ('student','Student','Учебный кабинет студента'),
          ('teacher','Teacher','Учебный кабинет преподавателя')
        ON CONFLICT(code) DO NOTHING
        """)
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS students (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id bigint REFERENCES users(id) ON DELETE SET NULL,
          university_id bigint NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
          program_id bigint REFERENCES programs(id) ON DELETE SET NULL,
          full_name varchar(250) NOT NULL,
          email citext NOT NULL,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        )
        """)
        await conn.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_students_university_id ON students(university_id)")
        await conn.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_students_program_id ON students(program_id)")
        await conn.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_students_email ON students(email)")
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS workflow_instances (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          interaction_id bigint NOT NULL UNIQUE REFERENCES interactions(id) ON DELETE CASCADE,
          template_id bigint NOT NULL REFERENCES workflow_templates(id) ON DELETE RESTRICT,
          template_version integer NOT NULL,
          started_at timestamptz NOT NULL DEFAULT now(),
          completed_at timestamptz
        )
        """)
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS workflow_transition_requests (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          interaction_id bigint NOT NULL REFERENCES interactions(id) ON DELETE CASCADE,
          stage_instance_id bigint NOT NULL REFERENCES workflow_stage_instances(id) ON DELETE CASCADE,
          target_stage_instance_id bigint REFERENCES workflow_stage_instances(id) ON DELETE SET NULL,
          requested_by bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
          transition_kind varchar(30) NOT NULL DEFAULT 'status_change' CHECK(transition_kind IN ('status_change','rollback')),
          from_status stage_status NOT NULL,
          to_status stage_status NOT NULL,
          comment text,
          status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
          reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
          reviewed_at timestamptz,
          review_comment text,
          created_at timestamptz NOT NULL DEFAULT now()
        )
        """)
        await conn.exec_driver_sql("CREATE INDEX IF NOT EXISTS ix_wtr_status ON workflow_transition_requests(status)")
        await conn.exec_driver_sql("ALTER TABLE workflow_transition_requests ADD COLUMN IF NOT EXISTS transition_kind varchar(30) NOT NULL DEFAULT 'status_change'")
        await conn.exec_driver_sql("ALTER TABLE workflow_transition_requests ADD COLUMN IF NOT EXISTS target_stage_instance_id bigint REFERENCES workflow_stage_instances(id) ON DELETE SET NULL")
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS workflow_transition_history (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          interaction_id bigint NOT NULL REFERENCES interactions(id) ON DELETE CASCADE,
          from_stage_instance_id bigint REFERENCES workflow_stage_instances(id) ON DELETE SET NULL,
          to_stage_instance_id bigint NOT NULL REFERENCES workflow_stage_instances(id) ON DELETE CASCADE,
          action varchar(20) NOT NULL,
          user_id bigint REFERENCES users(id) ON DELETE SET NULL,
          comment text,
          created_at timestamptz NOT NULL DEFAULT now()
        )
        """)
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS workflow_template_transitions (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          template_id bigint NOT NULL REFERENCES workflow_templates(id) ON DELETE CASCADE,
          from_stage_id bigint NOT NULL REFERENCES workflow_template_stages(id) ON DELETE CASCADE,
          to_stage_id bigint NOT NULL REFERENCES workflow_template_stages(id) ON DELETE CASCADE,
          condition_code varchar(100),
          label varchar(200),
          UNIQUE(template_id, from_stage_id, to_stage_id)
        )
        """)
        await conn.exec_driver_sql("""
        CREATE TABLE IF NOT EXISTS integration_runs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source varchar(20) NOT NULL CHECK(source IN ('lms','site')),
          direction varchar(20) NOT NULL CHECK(direction IN ('inbound','outbound')),
          status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','success','failed')),
          records_total integer NOT NULL DEFAULT 0,
          records_created integer NOT NULL DEFAULT 0,
          records_updated integer NOT NULL DEFAULT 0,
          records_skipped integer NOT NULL DEFAULT 0,
          error_message text,
          started_by bigint REFERENCES users(id) ON DELETE SET NULL,
          started_at timestamptz NOT NULL DEFAULT now(),
          finished_at timestamptz
        )
        """)
        await conn.exec_driver_sql("""
        INSERT INTO permissions(code, description) VALUES
          ('crm.read.assigned','Чтение доступных вузов и взаимодействий'),
          ('crm.write.assigned','Изменение доступных вузов и взаимодействий'),
          ('crm.approval','Подтверждение переходов workflow'),
          ('crm.users.roles','Управление пользователями и ролями')
        ON CONFLICT(code) DO NOTHING
        """)
        await conn.exec_driver_sql("""
        INSERT INTO role_permissions(role_id, permission_id)
        SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
        WHERE r.code='manager' AND p.code IN ('crm.read.assigned','crm.write.assigned')
        ON CONFLICT DO NOTHING
        """)
        await conn.exec_driver_sql("""
        INSERT INTO role_permissions(role_id, permission_id)
        SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
        WHERE r.code='leader' AND p.code IN ('crm.read.assigned','crm.write.assigned','crm.approval')
        ON CONFLICT DO NOTHING
        """)
        await conn.exec_driver_sql("""
        INSERT INTO role_permissions(role_id, permission_id)
        SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
        WHERE r.code='admin' AND p.code IN ('crm.read.assigned','crm.write.assigned','crm.approval','crm.users.roles')
        ON CONFLICT DO NOTHING
        """)
        # Interaction fields required by the updated specification; keep old columns intact.
        for sql in [
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS responsible_user_id bigint REFERENCES users(id) ON DELETE SET NULL",
          "UPDATE interactions SET responsible_user_id = owner_user_id WHERE responsible_user_id IS NULL AND owner_user_id IS NOT NULL",
          "ALTER TABLE interactions ALTER COLUMN program_id DROP NOT NULL",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS workflow_template_id bigint REFERENCES workflow_templates(id) ON DELETE RESTRICT",
          "UPDATE interactions SET workflow_template_id = template_id WHERE workflow_template_id IS NULL",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS transfer_status varchar(60) DEFAULT 'not_started'",
          "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'interactions_transfer_status_check') THEN ALTER TABLE interactions ADD CONSTRAINT interactions_transfer_status_check CHECK (transfer_status IS NULL OR transfer_status IN ('not_started','preparing','transferred','accepted')); END IF; END $$",

          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS vendor_id bigint REFERENCES vendors(id) ON DELETE SET NULL",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS contract_number varchar(150)",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS contract_signed_at timestamptz",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS license_signed_at timestamptz",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS license_valid_until timestamptz",
          "ALTER TABLE interactions ADD COLUMN IF NOT EXISTS transfer_status varchar(60) DEFAULT 'not_started'",
        ]:
            await conn.exec_driver_sql(sql)
